# Generated by Django 5.2.8 on 2025-11-25 01:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('fertilizante', 'Fertilizante'), ('pesticida', 'Pesticida'), ('herbicida', 'Herbicida'), ('fungicida', 'Fungicida'), ('semilla', 'Semilla'), ('abono', 'Abono Orgánico'), ('combustible', 'Combustible'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('unidad', 'Unidad'), ('bulto', 'Bulto'), ('galon', 'Galón'), ('tonelada', 'Tonelada')], default='kg', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=2, help_text='Nivel mínimo de stock para alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad de medida', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote_proveedor', models.CharField(blank=True, max_length=100)),
                ('requiere_receta', models.BooleanField(default=False, help_text='Requiere receta o autorización especial')),
                ('toxico', models.BooleanField(default=False)),
                ('periodo_carencia', models.IntegerField(blank=True, help_text='Días de carencia antes de cosecha', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='insumos_ins_codigo_6dacb7_idx'), models.Index(fields=['categoria', 'activo'], name='insumos_ins_categor_984868_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('aplicador', models.CharField(blank=True, help_text='Persona que aplicó el insumo', max_length=200)),
                ('dosis_aplicada', models.CharField(blank=True, help_text='Ejemplo: 2L/ha, 50g/planta', max_length=100)),
                ('condiciones_clima', models.CharField(blank=True, help_text='Condiciones climáticas durante la aplicación', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='tarea.tarea')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-fecha_consumo'],
                'indexes': [models.Index(fields=['insumo', 'tarea'], name='insumos_con_insumo__446cb4_idx'), models.Index(fields=['fecha_consumo'], name='insumos_con_fecha_c_6027df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('documento_referencia', models.CharField(blank=True, help_text='Número de factura, orden de compra, etc.', max_length=100)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('responsable', models.CharField(max_length=200)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['insumo', 'tipo', 'fecha'], name='insumos_mov_insumo__58ad21_idx')],
            },
        ),
    ]
