# Generated by Django 5.2.8 on 2025-11-26 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identificación solo debe contener dígitos', regex='^[0-9]+$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('rol', models.CharField(choices=[('operario', 'Operario'), ('tecnico', 'Técnico Agrícola'), ('supervisor', 'Supervisor'), ('maquinista', 'Operador de Maquinaria'), ('especialista', 'Especialista'), ('jefe_campo', 'Jefe de Campo')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('por_obra', 'Por Obra'), ('jornalero', 'Jornalero')], default='temporal', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario base mensual', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_hora', models.DecimalField(decimal_places=2, help_text='Valor por hora trabajada', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('especialidades', models.TextField(blank=True, help_text='Especialidades o habilidades especiales')),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones profesionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['rol', 'activo'], name='trabajadore_rol_5a0d41_idx'), models.Index(fields=['numero_identificacion'], name='trabajadore_numero__94fe1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('horas_asignadas', models.DecimalField(decimal_places=2, help_text='Horas asignadas para esta tarea', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, help_text='Horas realmente trabajadas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rol_en_tarea', models.CharField(blank=True, help_text='Rol específico en esta tarea', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tarea.tarea')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['trabajador', 'completada'], name='trabajadore_trabaja_4c76d3_idx'), models.Index(fields=['tarea', 'fecha_asignacion'], name='trabajadore_tarea_i_a105fd_idx')],
                'unique_together': {('trabajador', 'tarea')},
            },
        ),
    ]
