# Generated by Django 5.2.8 on 2025-11-21 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ubicacion', models.CharField(help_text='Dirección o coordenadas', max_length=500)),
                ('area_total', models.DecimalField(decimal_places=2, help_text='Área total en hectáreas', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud (georreferenciación)', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud (georreferenciación)', max_digits=10, null=True)),
                ('propietario', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área del lote en hectáreas', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cultivo_actual', models.CharField(blank=True, help_text='Cultivo actual del lote', max_length=100)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('preparacion', 'En Preparación'), ('sembrado', 'Sembrado'), ('crecimiento', 'En Crecimiento'), ('cosecha', 'Listo para Cosecha'), ('barbecho', 'En Barbecho'), ('inactivo', 'Inactivo')], default='preparacion', max_length=20)),
                ('coordenadas_poligono', models.TextField(blank=True, help_text='Coordenadas del polígono en formato JSON')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fincas.finca')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['finca', 'codigo'],
            },
        ),
    ]
