# Generated by Django 5.2.8 on 2025-11-21 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('preparacion', 'Preparación del Terreno'), ('siembra', 'Siembra'), ('mantenimiento', 'Mantenimiento'), ('fertilizacion', 'Fertilización'), ('control_plagas', 'Control de Plagas'), ('riego', 'Riego'), ('poda', 'Poda'), ('cosecha', 'Cosecha'), ('postcosecha', 'Postcosecha')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_estimada_horas', models.DecimalField(decimal_places=2, help_text='Duración estimada en horas', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('requiere_maquinaria', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='fincas.lote')),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='tarea.tipotarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_programada', 'prioridad'],
                'indexes': [models.Index(fields=['fecha_programada', 'estado'], name='tarea_tarea_fecha_p_8fb522_idx'), models.Index(fields=['lote', 'estado'], name='tarea_tarea_lote_id_4cd226_idx')],
            },
        ),
    ]
